### PR TITLE
Remove KURE's MonadCatch in favor of the one from exceptions (fixes #3)

### LINKED ISSUE #3: Replace MonadCatch with the one in the exceptions library?
Currently, `kure` defines its own `MonadCatch` class, which I think could be improved in a couple of ways:

1. There should be `MonadCatch` instances for all the data types in `transformers` to make it amenable for use with monad transformer stacks.
2. Instead of having the function argument to `catchM` be a `String`, which doesn't tell you much about the specific error is, `catchM` should provide an `Exception` as an argument. (For example, this would allow us to dispatch different types of errors more easily in `hermit-shell`.)

One way to fix both of these would be using the existing `MonadCatch` class defined in the `exceptions` library, which is [pretty widely used](http://packdeps.haskellers.com/reverse/exceptions). `MonadCatch` is defined as follows:

```haskell
class MonadThrow m => MonadCatch m where
  catch :: Exception e => m a -> (e -> m a) -> m a 
```

`exceptions` specifies the following law for `MonadCatch` instances: `catch (throwM e) f = f e`, where `throwM` is defined as:

```haskell
class Monad m => MonadThrow m where
  throwM :: Exception e => e -> m a
  -- obeys the following law
  -- throwM e >> x = throwM e
```

This more-or-less conforms to the semantics of the existing `MonadCatch` in `kure`, so they should be compatible. We'd have to change the semantics of several `MonadCatch` instances in `kure` in order to make this change work (e.g., we have have to `show` an `Exception` in places where `kure` is expecting a `String`), but nothing too drastic.

@Sculthorpen, what are your thoughts on this proposal?

### PR DESCRIPTION
**Pull request by RyanGlScott**
This is my attempt at converting KURE's `MonadCatch` from catching `String`s to catching `Exception`s (using the [`exceptions`](http://hackage.haskell.org/package/exceptions) library).

The bulk of the changes occur in `Language.KURE.MonadCatch`, since `KureM` had to be augmented in order to keep track of which `Exception` was last thrown. To accomplish this, I changed `KureM`'s definition to:

```haskell
data KureM a = Failure MsgException | Success a

data MsgException = MsgException String SomeException
```

`MsgException` needs to track which `Exception` was thrown last, which is why it has an underlying `SomeException`. But it also needs the ability to aggregate error messages, which is why it also contains a `String` à la the original `KureM`. The presence of a `String` means that you don't have to change too many type signatures (I had to change some `Monad` constraints to `MonadThrow`, but that was about it). The downside is that `KureM` can no longer be an `Eq` instance, but I think that's a small price to pay.

Critically, `MsgException` can be used to catch _any_ exception, and its underlying `SomeException` can be caught on its own, which allow `modFailMsg`, `setFailMsg`, `prefixFailMsg`, and `withPatFailMsg` to work:

```haskell
modFailMsg :: MonadCatch m => (String -> String) -> m a -> m a
modFailMsg f ma = ma `catch` \me@MsgException{} -> throwM (modMsgException f me)

setFailMsg :: MonadCatch m => String -> m a -> m a
setFailMsg ex = modFailMsg (const ex)

prefixFailMsg :: MonadCatch m => String -> m a -> m a
prefixFailMsg msg = modFailMsg (msg ++)

withPatFailMsg :: MonadCatch m => String -> m a -> m a
withPatFailMsg msg ma = ma `catch` \PatternMatchFail{} -> throwM (mkMsgException msg KureException)
```

`withPatFailMsg` is much cleaner now, and works with `KureM` due to its new `fail` implementation:

```haskell
-- | Throws a 'MsgException' with a blank error message.
fail :: String -> KureM a
fail str = Failure $ mkMsgException str (PatternMatchFail str)
```

Also, `withPatFailMsg` replaces the underlying `PatternMatchFail` exception with `KureException` (your suggested congruence combinator), so `withPatFailMsg` won't mistakenly catch a monadic action that was also surrounded by `withPatFailMsg` unless another genuine pattern-match failure occurs. `KureException` also permits a definition of another congruence combinator:

```haskell
-- | Catches a monadic action only if it throws a 'KureException'.
(<+>) :: MonadCatch m => m a -> m a -> m a
ma <+> mb = ma `catch` \KureException -> mb
```

All of the other changes are adding `MonadThrow`/`MonadCatch`/`MonadMask` instances and making small tweaks to the examples.

Let me know what you think. I believe I struck a good balance between adding new features and avoiding breakage of existing code, but I want to make sure these changes adhere to the original spirit of KURE.

### CODE REVIEW

**Comment by Sculthorpen** [comment]
Looking good.

I have one proposed change.  I don't think accumulating an error message string should be inherent to KURE.  Better to have KURE produce an exception containing the structure of the error, and let the consumer build their own error message from that.

With that in mind, I think we should generalise the basic infrastructure to arbitrary exceptions:

```haskell
data KureM a = Failure SomeException | Success a

setExc :: (Exception e, MonadCatch m) => e -> m a -> m a
modExc :: (Exception e1, Exception e2, MonadCatch m) => (e1 -> e2) -> m a -> m a
withPatFailExc :: (Exception e, MonadCatch m) => e -> m a -> m a
```

I think there are two notions of failure that are inherent to KURE: node mismatches and strategy failures. Thus I think we should provide the following two exception types:

```haskell
data NodeMismatch = NodeMismatch String

data StrategyFailure = StrategyFailure String (Maybe SomeException)
```
(Aside: Do you know why the exception types in `Control.Exception` use `data` rather than `newtype`?)

These exceptions include a `String` to record the name of the mismatched node or failing strategy, but this is not intended to be an error message as such.

We should probably define some combinators rather than using the constructors directly:

```haskell
nodeMismatch :: String -> NodeMismatch
nodeMismatch = NodeMismatch

strategyFail :: String -> StrategyFailure
strategyFail s = StrategyFailure s Nothing

stackStrategyFail :: String -> SomeException -> StrategyFailure
stackStrategyFail s = StrategyFailure s . Just
```
(Maybe these names could be improved.)

Example usage:

```haskell
(<+>) :: MonadCatch m => m a -> m a -> m a
ma <+> mb = ma `catch` \ (NodeMismatch _) -> mb

varT f = contextfreeT $ \case
                           Var n -> return (f n)
                           _     -> throwM (nodeMismatch "Var")

anytdR r = setExc (strategyFail "anytdR") $
           let go = r >+> anyR go
            in go

alltdR r = modExc (stackStrategyFail "alltdR") $
           let go = r >>> allR go
            in go
```

The existing "failMsg" combinators can be redefined in terms of `setExc`/`modExc` etc...  However, as I don't think they're inherent to KURE, I suggest moving them into HERMIT, perhaps along with the `MsgException` you proposed.  HERMIT can decide whether it wants to continue to use them, or whether it wants to migrate to the new combinators above.  I imagine HERMIT may want to introduce its own additional exception types anyway.

Finally, while I don't think error messages should be hard-wired into KURE, for the benefit of a new KURE user it would probably be helpful to define some show-like functions that produce a default error message, that more or less corresponds to the error messages that we were producing before.  E.g.

```haskell
runAndShowKureM :: Show a => KureM a -> String
runAndShowKureM (Failure e) = "KURE Failure: " ++ showKureExc e
runAndShowKureM (Success a) = "KURE Success: " ++ show a

showKureExc :: SomeException -> String
showKureExc e =
  case cast e of
    Just (NodeMismatch n) -> "node mismatch, not a " ++ n ++ " node."
    Nothing -> case cast e of
                 Just (StrategyFailure s Nothing)  -> s ++ " strategy failed." 
                 Just (StrategyFailure s (Just e)) -> s ++ " strategy failed, because " ++ showKureExc e
                 Nothing                           -> "unrecognised exception."
```
(Maybe some of the above should be factored into `displayException`.)


How does that all sound?

Neil

**Comment by RyanGlScott** [comment]
That all sounds good to me, although I'm not sure I understand the distinction between `strategyFail` and `stackStrategyFail`. Under what circumstances would you want to throw away an exception with `strategyFail` (`anytdR` being an example)?

> (Aside: Do you know why the exception types in `Control.Exception` use `data` rather than `newtype`?)

Good question. Oversight, perhaps? Previous commits to GHC have changed `data`→`newtype` in the particular cases of [`ErrorCall`](http://git.haskell.org/ghc.git/blobdiff/1e1c03fadd11a1a7032d1e34f55b17205fe62308..3c083fae0833ba222dc5c36cb04f2a9d88e39c86:/libraries/base/GHC/Exception.lhs) and [`Timeout`](https://ghc.haskell.org/trac/ghc/ticket/4961), so maybe no one's ever noticed the remaining ones in `Control.Exception`. I'll file a ticket for this when I get a chance.

**Comment by Sculthorpen** [comment]
It is for the same reason that previously we used both `setFailMsg` and `prefixFailMsg`.

The `alltdR` strategy is expected to succeed everywhere, so if it fails anywhere it is useful to report the cause of the failure.  Thus we use `stackStrategyFail`.

On the other hand, the `anytdR` strategy is allowed to fail in many places, provided it succeeds at least once.  In the situation it fails everywhere, is not very meaningful to return the exception information about just one of those failures.  Thus we use `strategyFail`.

**Comment by RyanGlScott** [comment]
OK, I went ahead and rewrote a lot of the type signatures to incorporate exceptions. As a result, `fail` isn't used much anymore in KURE, many type signatures were changed from `(Monad m) => String -> ...` to `(Exception e, MonadThrow m) => e -> ...`, and several function names now have a `FailExc` suffix instead of `FailMsg`.

I'd appreciate if you could do a style check on a couple of things on which I had to make judgment calls:

1. There were a couple of error messages that didn't seem to neatly fit into `NodeMismatch` or `StrategyFailure`, so I created a third exception type `ConditionalFailure` for those cases. It's pretty catch-all, so if you have a preference for some other classification of these errors, I'm all ears.
2. The output of `showKureExc` _could_ be different on GHCs before GHC 7.10, since `displayException` wasn't around back then (I use `show` as a workaround on old GHCs). For KURE-specific exception types, this won't make a difference, but if other exception types are thrown into the mix, you could get different output on different GHCs. Do you think I should just always use `show`?

**Comment by Sculthorpen** [comment]
(1)  `ConditionalFailure` seems reasonable.
(2)  I'm not worried about differing error message strings on older GHCs, so if that is the only problem then let's look forwards and use `displayException` when on GHC  >= 7.10.

I've made a few adjustments:
- The notion of failure is strategic programming terminology, regardless of whether that is handled internally using `fail` or `throwM`, so I reverted a few comments to reflect that.
- I had a slightly different intent with the `NodeMismatch` and `StrategyFailure` exceptions, and have adjusted their uses accordingly.

I'm fairly happy with it now, but let me know if you have any further comments/suggestions.  When I  release this to Hackage, I will increment the major version number, as this is a fairly substantial change.

First however, we should think about integrating these changes into HERMIT.

**Comment by RyanGlScott** [comment]
Thanks for the very thorough style check! I'm also happy with the way it turned out.

I agree that we should probably publish these changes in conjunction with a HERMIT overhaul, which I'd be willing to take a crack at after I gain some free time.

To make sure I have this in my head: your intention is to always use a `StrategyFailure` at the bottom of an exception stack wherever a `fail` with a strategy name is encountered? (e.g., `fail "fooR: some explanation here"`) And use `ConditionalFailure` whenever there's a lone explanation for why something failed? (e.g., `fail "some explanation here"`)

**Comment by Sculthorpen** [comment]
I'm not sure I entirely understand your question, but my approach has been for each named strategy (typically the name of the Haskell function) to throw a `StrategyFailure` if it fails.  Whether that contains a sub-exception depends on whether there is more than one way the strategy could fail.  I changed several bits of your code where you were putting a `ConditionalFailure` inside a `StrategyFailure` because there was only one way the strategy could fail, making the `ConditionalFailure` information redundant.  The contents of a `StrategyFailure` is always just the strategy name (to facilitate pretty printing by a consumer), whereas the contents of a `ConditionalFailure` is an arbitrary error message.

In HERMIT, I expect changes as follows:

Previously: `fail "explanation"`
Now: `throwM (conditionalFailure "explanation")

Previously: `fail "fooR failed"`
Now: `throwM (strategyFailure "fooR")`

Previously: `setFailMsg "fooR failed"`
Now: `setExc (strategyFailure "fooR")`

Previously: `prefixFailMsg "fooR failed: "`
Now: `modExc (stackStrategyFailure "fooR")`

Though it doesn't matter too much whether `StrategyFailure` or `ConditionalFailure` is used, as that just affects the resulting error message.  What is important is that `NodeFailure` is only used when defining congruence combinators, to ensure the correct behaviour of `(<+>)`.  However, I suggest that initially we just update the exceptions without updating any uses of `(<+)` to `(<+>)`.  Once that's all tested and working, then we can try introducing `(<+>)`, which is essentially an optimisation.

**Comment by Sculthorpen** [comment]
In anticipation of this change, I've set the upper bound of HERMIT's dependency on KURE to "kure <3.0".  Then if there's another HERMIT release before these changes are incorporated, it should still be safe to release the new KURE as version 3.0.

**Comment by Sculthorpen** [comment]
I'd like to go ahead and merge the exceptions branch into the master branch.  I will release a version 2.16.12 that reflects the current state of the master branch first, as I assume you're using those Typeable instances that you added in May.  Do you have any objection to this plan?

**Comment by RyanGlScott** [comment]
No objections on my end!

**Pull request merged**
